import { Car } from "../components/CarCards";
export const allCars: Car[] = [
    {
        id: 1,
        name: "Toyota Kluger",
        image: "https://i.ibb.co.com/67XySQmJ/suv-toyota-kluger.jpg",
        seats: "5-7 seats",
        luggage: "4-5 medium bags",
        idealFor: "Road trips or city driving. Spacious and comfortable for long journeys or family trips.",
        perfectFor: "Families or groups looking for flexibility in seating and ample luggage space.",
        transmission: "Automatic",
        price: 50,
        type: "SUV",
    },
    {
        id: 2,
        name: "Toyota RAV4",
        image: "https://i.ibb.co.com/MDTjW81M/suv-toyota-rav4.jpg",
        seats: "5 seats",
        luggage: "3 medium bags",
        idealFor: "City driving and short trips. Compact, efficient, and easy to navigate urban streets.",
        perfectFor: "Individuals or small groups seeking a versatile, fuel-efficient SUV.",
        transmission: "Automatic",
        price: 50,
        type: "SUV",
    },
    {
        id: 3,
        name: "Ford Territory",
        image: "https://i.ibb.co.com/9HJ9sMRc/suv-ford-territory.jpg",
        seats: "5 or 7 seats",
        luggage: "4-5 medium bags",
        idealFor: "Road trips or city driving. Offers a smooth drive and plenty of room for passengers and luggage.",
        perfectFor: "Families or groups requiring extra space and comfort.",
        transmission: "Automatic",
        price: 50,
        type: "SUV",
    },
    {
        id: 4,
        name: "Mitsubishi Outlander",
        image: "https://i.ibb.co.com/GvZkYqtp/suv-mitsubishi-outlander.jpg",
        seats: "5 or 7 seats",
        luggage: "4 medium bags",
        idealFor: "Road trips and city driving. Known for its fuel efficiency and flexibility in seating arrangements.",
        perfectFor: "Families or small groups seeking a reliable, spacious SUV for all occasions.",
        transmission: "Automatic",
        price: 50,
        type: "SUV",
    },
    {
        id: 5,
        name: "Mitsubishi ASX",
        image: "https://i.ibb.co.com/SDpYGZWZ/suv-mitsubishi-asx.jpg",
        seats: "5 seats",
        luggage: "3 medium bags",
        idealFor: "City driving and short trips. A compact SUV that offers great maneuverability in busy city environments.",
        perfectFor: "Individuals or small families who need an affordable and fuel-efficient vehicle.",
        transmission: "Automatic",
        price: 50,
        type: "SUV",
    },
    {
        id: 6,
        name: "Holden Caprice",
        image: "https://i.ibb.co.com/Zp2Dcvsn/sedan-holden-caprice.jpg",
        seats: "5 seats",
        luggage: "3-4 medium bags",
        idealFor: "Road trips or city driving. Offers luxury comfort and a smooth ride for longer journeys.",
        perfectFor: "Those looking for a premium experience and extra comfort while traveling.",
        transmission: "Automatic",
        price: 50,
        type: "Sedan",
    },
    {
        id: 7,
        name: "Suzuki Kizashi",
        image: "https://i.ibb.co.com/HDn6vtX6/sedan-suzuki-kizashi.jpg",
        seats: "5 seats",
        luggage: "3 medium bags",
        idealFor: "City driving and short trips. Compact, efficient, and great for urban commuting.",
        perfectFor: "Individuals or couples looking for an economical and reliable vehicle.",
        transmission: "Automatic",
        price: 50,
        type: "Sedan",
    },
    {
        id: 8,
        name: "Holden Malibu",
        image: "https://i.ibb.co.com/Y458pr0N/sedan-holden-malibu.jpg",
        seats: "5 seats",
        luggage: "3 medium bags",
        idealFor: "City driving and short trips. Sleek design with great fuel efficiency for daily use.",
        perfectFor: "Those seeking a stylish sedan for everyday city commutes.",
        transmission: "Automatic",
        price: 50,
        type: "Sedan",
    },
    {
        id: 9,
        name: "Holden Cascada",
        image: "https://i.ibb.co.com/35fkcd2y/convertible-holden-cascada.jpg",
        seats: "4 seats",
        luggage: "2-3 small bags",
        idealFor: "Short trips and city driving. Perfect for those looking to enjoy the open air during their drive.",
        perfectFor: "Couples or individuals who want a fun, stylish driving experience.",
        transmission: "Automatic",
        price: 50,
        type: "Convertible",
    },
    {
        id: 10,
        name: "Holden Cruze",
        image: "https://i.ibb.co.com/xqzLsdX9/hatchback-holden-cruze.jpg",
        seats: "5 seats",
        luggage: "2-3 small bags",
        idealFor: "City driving and short trips. Compact and easy to park, perfect for daily commutes.",
        perfectFor: "Individuals or families who need a practical and economical car for city use.",
        transmission: "Automatic",
        price: 50,
        type: "Hatchback",
    },
    {
        id: 11,
        name: "Nissan Navara",
        image: "https://i.ibb.co.com/prd9GKJm/suv-nissan-navara.jpg",
        seats: "5 seats",
        luggage: "3-4 medium bags or cargo in the tray",
        idealFor: "Work, outdoor adventures, or moving larger items. Offers durability and versatility for various needs.",
        perfectFor: "Tradespeople, outdoor enthusiasts, or anyone needing a tough, reliable utility vehicle.",
        transmission: "Manual",
        price: 50,
        type: "UTEs & Trucks",
    },
];
